[package]
name = "codecrafters-dns-server"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.88"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
thiserror = "2.0.16"
rand = "0.9.2"

[lints.clippy]
bool_assert_comparison = "allow"
